# Site settings
title: Vishnu Das Bharathraj
logo: /assets/img/vishdaslin.jpeg
description: Generative AI Engineer
show_downloads: true
logo: /assets/img/vishdas.png  # Add your profile picture or logo here
theme: jekyll-theme-minimal
