# Site settings
title: Vishnu Das Bharathraj
description: Gen-AI Engineer | Cloud Data Engineer | Data Scientist
url: "https://vishnudas.com"
baseurl: ""

# Theme settings
theme: jekyll-theme-minimal
logo: /assets/img/vishdas.png

# Social media links
social_links:
  linkedin: https://www.linkedin.com/in/vishdas/
  github: https://github.com/vishdas-ai
  email: vishnudas1297@gmail.com

# Resume download link
resume_link: /assets/Vishnu_Das_Resume.pdf

# Google Analytics
google_analytics: UA-XXXXXXXX-X  # Replace with your Google Analytics tracking ID

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
nav:
  - {name: 'Home', link: '/'}
  - {name: 'Projects', link: '/projects'}
  - {name: 'Blog', link: '/blog'}
  - {name: 'Contact', link: '/contact'}

# Skills
skills:
  - Python
  - SQL
  - Spark
  - R
  - Machine Learning
  - Deep Learning
  - MSSQL
  - Hadoop
  - Hive
  - PyTorch
  - TensorFlow
  - Docker
  - HTML
  - Git
  - GCP
  - Cloud Computing
  - Terraform
  - Airflow
  - CI/CD
  - Informatica Cloud Integration
  - Unit Testing
  - Generative AI
  - NLP
  - FastAPI
  - Large Language Models
  - Langchain
  - llama-Index
  - Haystack
  - Computer Vision

# Custom CSS
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
